### ISSUE TITLE
Debug log option not working correctly

### ISSUE THREAD

**Issue by visudo20179C** [Arsenal21/simple-wp-shopping-cart#1]
I have checked the box to enable debug on WP Paypal Shopping Cart Options v4.4.8
in my wordpress admin panel. Yet nothing is being logged to the file when I am triggering IPN and webhook events from my PayPal developer account. The only thing that is logged to this file is the message when you click "Reset debug log file". Please help.

**Comment by Arsenal21** [comment]
Do you have the PayPal IPN notification enabled in your PayPal account?
https://www.tipsandtricks-hq.com/ecommerce/how-to-setup-paypal-ipn-notification-2796

**Comment by visudo20179C** [comment]
No, I am not using a personal account for testing. I am using a sandbox account to send test IPNs to my handler which uses the built-in handler class that comes with the plugin in paypal.php. On the PayPal Developer side the IPNs are being processed correctly but cannot confirm this without looking at the handler logs. If this plugin does not support sandbox testing please let me know.

**Comment by Arsenal21** [comment]
Sandbox testing works fine. I used that myself when I am doing some testing. I know 100% the plugin is working as I use it on my test site (with sandbox setup) and on a different site in live mode. You can try a different plugin if you want.

**Comment by visudo20179C** [comment]
Cool.... thanks dawg. There must be something that I am doing wrong with my testing..... I am really new to the WordPress world..... sorry if I wasted your time dawg.... keep it young.
