### ISSUE TITLE
Problem with multiple items in one cart

### ISSUE THREAD

**Issue by visudo20179C** [Arsenal21/simple-wp-shopping-cart#4]
Hello. I've been using this plugin with great success. However one issue I come across is when the user checks out with multiple items in their cart. When this happens, we don't receive an IPN payload like we do if the user just bought one item. Please let me know if there is anything you can do.

**Comment by Arsenal21** [comment]
PayPal sends slightly different IPN for one item checkout vs multiple items checkout. The plugin can handle both those IPNs. I just tested a multiple item checkout just now to verify that it is working fine.

You don't see the order data in the orders menu of the plugin when you do a checkout with multiple items? Do you have another plugin that maybe taking the IPN of multiple items one and then this plugin is never receiving it?

**Comment by visudo20179C** [comment]
We can still see the order data in the dashboard table for orders with multiple items. It's the IPN payload we are not seeing come through in the ipn_handle_debug.txt file like we are with single item orders. There is no other plugin that we are using that I am aware would cause this sort of behavior. I will continue to test to see if I can isolate the cause and provide any additional information.

**Comment by visudo20179C** [comment]
is there any advice that you could give on handling multi-item orders with this plugin? I tried to make a loop but it seems the IPN payload is delivered as a string.
